version: "3.9"

services:
  mysql:
    image: mysql:8.4.0          # 최신 LTS
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: babzipdb
      MYSQL_ROOT_PASSWORD: "babzippass"
      MYSQL_USER: babzip
      MYSQL_PASSWORD: "babzippass"
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      # ────────── Host  ➜  Container ──────────
      - ./docker-infra/mysql/data:/var/lib/mysql      # 데이터 파일
      - ./docker-infra/mysql/config:/etc/mysql/conf.d # 사용자 정의 설정(.cnf)
