jwt:
  secret-key: Zr2PMyKH4UheWy6zscq6Wc/nSLl6L/AJ6b5QvLzWXJg5wzQiGdJncTTOBCxvW8Rkl1T0N+1bqF52Mw2eZvwA0i5zyq+VVbIjPyz+b7DW0Xd2wTnXifwxM12LU2oyXpyLz
  access-token-expire-in: 1800
  refresh-token-expire-in: 1209600

spring:
  security:
    oauth2:
      client:
        registration:
          google:
              client-id: 540803440273-6dtj5tfo86g1vj3vll8jvp6q450nvttr.apps.googleusercontent.com
              client-secret: ${GOOGLE_SECRET}
              scope: # google API의 범위 값
                - profile
                - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

