spring:
  config:
    activate:
      on-profile: dev
    import:
      - application-security.yml

  datasource:
    url: jdbc:mysql://localhost:3307/babzipdb
    username: babzip
    password: "babzippass"
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    log-request-details: true

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        highlight_sql: true
        default_batch_fetch_size: 100

